/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutOrdersRouteImport } from './routes/_layout/orders'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutMailRouteImport } from './routes/_layout/mail'
import { Route as LayoutKanbanRouteImport } from './routes/_layout/kanban'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutInvoicesRouteImport } from './routes/_layout/invoices'
import { Route as LayoutHelpSupportRouteImport } from './routes/_layout/help-support'
import { Route as LayoutFormsLibraryRouteImport } from './routes/_layout/forms-library'
import { Route as LayoutFormsRouteImport } from './routes/_layout/forms'
import { Route as LayoutFilesRouteImport } from './routes/_layout/files'
import { Route as LayoutCustomersRouteImport } from './routes/_layout/customers'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutChartsRouteImport } from './routes/_layout/charts'
import { Route as LayoutCalendarRouteImport } from './routes/_layout/calendar'
import { Route as LayoutBillingRouteImport } from './routes/_layout/billing'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout/analytics'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersRoute = LayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMailRoute = LayoutMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKanbanRoute = LayoutKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvoicesRoute = LayoutInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHelpSupportRoute = LayoutHelpSupportRouteImport.update({
  id: '/help-support',
  path: '/help-support',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormsLibraryRoute = LayoutFormsLibraryRouteImport.update({
  id: '/forms-library',
  path: '/forms-library',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormsRoute = LayoutFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFilesRoute = LayoutFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCustomersRoute = LayoutCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChartsRoute = LayoutChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalendarRoute = LayoutCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBillingRoute = LayoutBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/billing': typeof LayoutBillingRoute
  '/calendar': typeof LayoutCalendarRoute
  '/charts': typeof LayoutChartsRoute
  '/chat': typeof LayoutChatRoute
  '/customers': typeof LayoutCustomersRoute
  '/files': typeof LayoutFilesRoute
  '/forms': typeof LayoutFormsRoute
  '/forms-library': typeof LayoutFormsLibraryRoute
  '/help-support': typeof LayoutHelpSupportRoute
  '/invoices': typeof LayoutInvoicesRoute
  '/items': typeof LayoutItemsRoute
  '/kanban': typeof LayoutKanbanRoute
  '/mail': typeof LayoutMailRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/orders': typeof LayoutOrdersRoute
  '/profile': typeof LayoutProfileRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/billing': typeof LayoutBillingRoute
  '/calendar': typeof LayoutCalendarRoute
  '/charts': typeof LayoutChartsRoute
  '/chat': typeof LayoutChatRoute
  '/customers': typeof LayoutCustomersRoute
  '/files': typeof LayoutFilesRoute
  '/forms': typeof LayoutFormsRoute
  '/forms-library': typeof LayoutFormsLibraryRoute
  '/help-support': typeof LayoutHelpSupportRoute
  '/invoices': typeof LayoutInvoicesRoute
  '/items': typeof LayoutItemsRoute
  '/kanban': typeof LayoutKanbanRoute
  '/mail': typeof LayoutMailRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/orders': typeof LayoutOrdersRoute
  '/profile': typeof LayoutProfileRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/analytics': typeof LayoutAnalyticsRoute
  '/_layout/billing': typeof LayoutBillingRoute
  '/_layout/calendar': typeof LayoutCalendarRoute
  '/_layout/charts': typeof LayoutChartsRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/customers': typeof LayoutCustomersRoute
  '/_layout/files': typeof LayoutFilesRoute
  '/_layout/forms': typeof LayoutFormsRoute
  '/_layout/forms-library': typeof LayoutFormsLibraryRoute
  '/_layout/help-support': typeof LayoutHelpSupportRoute
  '/_layout/invoices': typeof LayoutInvoicesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/kanban': typeof LayoutKanbanRoute
  '/_layout/mail': typeof LayoutMailRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/orders': typeof LayoutOrdersRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/calendar'
    | '/charts'
    | '/chat'
    | '/customers'
    | '/files'
    | '/forms'
    | '/forms-library'
    | '/help-support'
    | '/invoices'
    | '/items'
    | '/kanban'
    | '/mail'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/calendar'
    | '/charts'
    | '/chat'
    | '/customers'
    | '/files'
    | '/forms'
    | '/forms-library'
    | '/help-support'
    | '/invoices'
    | '/items'
    | '/kanban'
    | '/mail'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/analytics'
    | '/_layout/billing'
    | '/_layout/calendar'
    | '/_layout/charts'
    | '/_layout/chat'
    | '/_layout/customers'
    | '/_layout/files'
    | '/_layout/forms'
    | '/_layout/forms-library'
    | '/_layout/help-support'
    | '/_layout/invoices'
    | '/_layout/items'
    | '/_layout/kanban'
    | '/_layout/mail'
    | '/_layout/notifications'
    | '/_layout/orders'
    | '/_layout/profile'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mail': {
      id: '/_layout/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof LayoutMailRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/kanban': {
      id: '/_layout/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof LayoutKanbanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invoices': {
      id: '/_layout/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof LayoutInvoicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/help-support': {
      id: '/_layout/help-support'
      path: '/help-support'
      fullPath: '/help-support'
      preLoaderRoute: typeof LayoutHelpSupportRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/forms-library': {
      id: '/_layout/forms-library'
      path: '/forms-library'
      fullPath: '/forms-library'
      preLoaderRoute: typeof LayoutFormsLibraryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/forms': {
      id: '/_layout/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof LayoutFormsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/files': {
      id: '/_layout/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof LayoutFilesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/customers': {
      id: '/_layout/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof LayoutCustomersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/charts': {
      id: '/_layout/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof LayoutChartsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calendar': {
      id: '/_layout/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof LayoutCalendarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/billing': {
      id: '/_layout/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof LayoutBillingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute
  LayoutBillingRoute: typeof LayoutBillingRoute
  LayoutCalendarRoute: typeof LayoutCalendarRoute
  LayoutChartsRoute: typeof LayoutChartsRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutCustomersRoute: typeof LayoutCustomersRoute
  LayoutFilesRoute: typeof LayoutFilesRoute
  LayoutFormsRoute: typeof LayoutFormsRoute
  LayoutFormsLibraryRoute: typeof LayoutFormsLibraryRoute
  LayoutHelpSupportRoute: typeof LayoutHelpSupportRoute
  LayoutInvoicesRoute: typeof LayoutInvoicesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutKanbanRoute: typeof LayoutKanbanRoute
  LayoutMailRoute: typeof LayoutMailRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutOrdersRoute: typeof LayoutOrdersRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAnalyticsRoute: LayoutAnalyticsRoute,
  LayoutBillingRoute: LayoutBillingRoute,
  LayoutCalendarRoute: LayoutCalendarRoute,
  LayoutChartsRoute: LayoutChartsRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutCustomersRoute: LayoutCustomersRoute,
  LayoutFilesRoute: LayoutFilesRoute,
  LayoutFormsRoute: LayoutFormsRoute,
  LayoutFormsLibraryRoute: LayoutFormsLibraryRoute,
  LayoutHelpSupportRoute: LayoutHelpSupportRoute,
  LayoutInvoicesRoute: LayoutInvoicesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutKanbanRoute: LayoutKanbanRoute,
  LayoutMailRoute: LayoutMailRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutOrdersRoute: LayoutOrdersRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
